import alias from './alias/index';
import audio from './audio/index';
import center from './center/index';
import debug from './debug/index';
import jump from './jump/index';
import left from './left/index';
import right from './right/index';
import scene from './scene/index';
import sound from './sound/index';
